name: Backend Code Quality

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"

  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"

  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .
